updated index page
Hexlet/RestApiTutorial.ru pull request #68
Opened 2021-06-13 15:26 UTC by Surtt

#63

2021-06-15 07:28 UTC, amshkv commented
а 78-105 что отступы не поправил в index? :)

2021-06-15 07:52 UTC, amshkv reviewed
Так, ты большой молодец, что взялся за это дело.
Предвижу тут миллион рабочих задачек, давай как-то делать это итерациями.
Для начала давай поправим что я написал, а дальше будем разбираться)

2021-06-15 07:52 UTC, amshkv commented on index.html
> +<body class="pt-0">
Смотри, у тебя в `style` в `head` есть паддинги для `body`, при этом ты для самого `body` один паддинг переопределяешь, кажется что что-то лишнее (инлайн стили)

2021-06-15 07:52 UTC, amshkv commented on lessons/whatisrest.html
> +  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
насколько я знаю, в 5м бутстрапе не нужен jquery, а тут мы его подключаем, ты уверен что оно нам надо? (тот же вопрос к popper.js)

2021-06-15 07:52 UTC, amshkv commented on index.html
> +    <div class="container-fluid mx-auto" style="width: 1170px;">
`style="width: 1170px;` - в случае с бутстрапом, инлайн стили скорее зло чем добро, зачем это тут?

2021-06-15 07:52 UTC, amshkv commented on index.html
> +      <a class="navbar-brand" href="http://www.restapitutorial.ru">Руководство по REST API</a>
. это разве не достаточно изменить на корень сайта? `href="http://www.restapitutorial.ru"` на href=/

2021-06-15 07:52 UTC, amshkv commented on index.html
> +    <div class="p-5 bg-light">
`container` > `p-5 bg-light` нам тут действительно нужны такие большие отступы?

2021-06-15 07:52 UTC, amshkv commented on index.html
> +      <a class="navbar-brand" href="http://www.restapitutorial.ru">Руководство по REST API</a>
изменится домен и все ссылки пойдут в какашку

2021-06-15 09:05 UTC, Surtt commented
> а 78-105 что отступы не поправил в index? :)

ты имеешь в виду закоментированный код? Удаляю его? :)

2021-06-15 09:06 UTC, amshkv commented
> ты имеешь в виду закоментированный код? Удаляю его? :)
удалять пока наверное не стоит)
смотрю ты отступы везде перекроил) а тут "старые отступы остались"
ну это так, мелкая придирка конечно же

2021-06-15 09:14 UTC, Surtt commented
> > ты имеешь в виду закоментированный код? Удаляю его? :)
> > удалять пока наверное не стоит)
> > смотрю ты отступы везде перекроил) а тут "старые отступы остались"
> > ну это так, мелкая придирка конечно же

а, ну так это закоментировано, я это даже не смотрел.

2021-06-15 09:24 UTC, Surtt commented on index.html
> +    <div class="container-fluid mx-auto" style="width: 1170px;">
> `style="width: 1170px;` - в случае с бутстрапом, инлайн стили скорее зло чем добро, зачем это тут?

Тут я не знаю как решить проблему с мобильной версией. Если удалить `style="width: 1170px;` и вместо `container-fluid` установить `container` тогда в мобилке меню ломается. Если совсем контейнер удалить, тогда ломается меню на десктопе

2021-06-23 09:31 UTC, fey commented
@amshkv если нет критичных моментв - смержу?

2021-06-23 09:52 UTC, amshkv requested changes
Смотри, давай удалим везде этот респонсив стил, поправим нав меню и немного шороху в футере наведем, прям чуть чуть, и в прод!)

2021-06-23 09:52 UTC, amshkv commented on index.html
> +  <link href="https://d7im4lln3lvbg.cloudfront.net/bootstrap/2.0.1/css/bootstrap-responsive.min.css" rel="stylesheet">
вот этот хитрый css старый ломает тебе всю верстку с нав меню

2021-06-23 09:52 UTC, amshkv commented on index.html
> +    <div class="container-fluid mx-auto" style="width: 1170px;">
тогда вот тут мы убираем твои инлайн стили, mx-auto и контейнер можем поменять на просто контейнер
и еще, я бы посоветовал бренд имя вынести перед кнопкой-тогглером

2021-06-23 09:52 UTC, amshkv commented on index.html
> +    <footer>
вот тут как-будто много стало и высоко, может до small сократим?
а еще лучше если отзывы каждого <p> подрежем, чтобы это таким полотном не было, а красоту потом наводить будем

2021-06-23 09:52 UTC, amshkv commented on lessons/whatisrest.html
> +  <link href="https://d7im4lln3lvbg.cloudfront.net/bootstrap/2.0.1/css/bootstrap-responsive.min.css" rel="stylesheet">
то же самое

2021-06-23 19:40 UTC, Surtt commented on index.html
> +    <footer>
> и еще, я бы посоветовал бренд имя вынести перед кнопкой-тогглером

Если бренд вынести перед кнопкой, тогда на мобилке бейджик гитхаб перекрывает меню (тоггл)

> вот тут как-будто много стало и высоко, может до small сократим?
а еще лучше если отзывы каждого
подрежем, чтобы это таким полотном не было, а красоту потом наводить будем

Это совсем не понял. Какие отзывы?

2021-06-23 19:59 UTC, Surtt commented on index.html
> +  <link href="https://d7im4lln3lvbg.cloudfront.net/bootstrap/2.0.1/css/bootstrap-responsive.min.css" rel="stylesheet">
> немного шороху в футере наведем, прям чуть чуть

не уверен, что немного получилось :)

2021-06-24 08:29 UTC, amshkv commented on index.html
> +  <footer class="bg-dark text-light p-4 mt-5">
`p-4` лишнее, лучше `py-4`, иначе текст криво выровнен будет

2021-06-24 08:55 UTC, merged